/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/input`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/checkbox`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useKeyboardHeight`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/avoid-keyboard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/text`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/view`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/bottom-sheet`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/icon`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/input`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/checkbox`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useKeyboardHeight`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/avoid-keyboard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/text`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/view`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/bottom-sheet`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/ui/icon${`?${string}` | `#${string}` | ''}` | `/../components/ui/input${`?${string}` | `#${string}` | ''}` | `/../components/ui/checkbox${`?${string}` | `#${string}` | ''}` | `/../hooks/useKeyboardHeight${`?${string}` | `#${string}` | ''}` | `/../components/ui/avoid-keyboard${`?${string}` | `#${string}` | ''}` | `/../components/ui/text${`?${string}` | `#${string}` | ''}` | `/../components/ui/view${`?${string}` | `#${string}` | ''}` | `/../components/ui/bottom-sheet${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/input`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/checkbox`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useKeyboardHeight`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/avoid-keyboard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/text`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/view`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/bottom-sheet`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
